### PR TITLE
Update to latest OpenAPI generator

### LINKED ISSUE #1: redeclared in this block
Hi,
I can't build...

` go build
# github.com/elasticemail/elasticemail-go
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_campaign_status.go:25:2: ACTIVE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_account_status_enum.go:27:2: other declaration of ACTIVE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_compression_format.go:24:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_hist_event_type.go:37:2: DELETED redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_campaign_status.go:24:2: other declaration of DELETED
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_status.go:26:2: ACTIVE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_account_status_enum.go:27:2: other declaration of ACTIVE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_status.go:27:2: BOUNCED redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_hist_event_type.go:26:2: other declaration of BOUNCED
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_status.go:28:2: UNSUBSCRIBED redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_contact_hist_event_type.go:27:2: other declaration of UNSUBSCRIBED
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_delivery_optimization_type.go:24:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_email_validation_status.go:24:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_email_validation_status.go:26:2: UNKNOWN redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_consent_tracking.go:24:2: other declaration of UNKNOWN
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_encoding_type.go:25:2: NONE redeclared in this block
	../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_access_level.go:24:2: other declaration of NONE
../../../../../pkg/mod/github.com/elasticemail/elasticemail-go@v0.0.0-20221129113952-edcf36f52e5c/model_encoding_type.go:25:2: too many errors`

### PR DESCRIPTION
**Pull request by beornf**
I have fixed compile errors due to redeclared variables by making two changes:
1. `enumClassPrefix=true` is passed as an additional property to prevent conflicts of `ACTIVE` and other constants.
2. Renaming the `NewApiKey` and `NewSmtpCredentials` models as they conflict with `NewApiKey()` and `NewSmtpCredentials()`.

Fixes #1.

### CODE REVIEW

**Comment by c9s** [comment]
omg this issue was created since last year, and no one from ElasticEmail reviews this LOL

**Comment by beornf** [comment]
The development team has zero communication with ElasticEmail customers in my experience 😆

**Comment by bakl** [comment]
still not reviewed? (

**Comment by radzawee** [comment]
Thank you for your effort, however we have just released new version, generated using OpenAPI Generator 7.7.0.

**Pull request closed without merging**
